// Generate ast-grep rules to migrate from the old `AstBuilder` to the new builder methods
// defined on AST types.
//
// Reads:
// * `generated/mappings.json` - generated by `AstBuilderGenerator` (`tasks/ast_tools`).
// * `custom_mappings.json` - hand-written mappings for methods not emitted by codegen.
//
// Writes:
// * `generated/rules.yml` - ast-grep rules, one per builder method.
//
// Each rule rewrites a call on the old builder to a call to the new method, appending the
// accessor (the base of the `<accessor>.ast` receiver) as the final argument:
//
//   self.ast.null_literal(span)             ->  NullLiteral::new(span, self)
//   p.ast.alloc_object_expression(span, x)  ->  ObjectExpression::boxed(span, x, p)
//   self.ast.number_0()                     ->  Expression::new_number_0(self)
//
// Run with:  `node tasks/ast_builder_migration/generate_rules.mts`
// Then apply with the `ast-grep scan` command it prints.

// oxlint-disable no-console

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dirname;

type CustomMappings = { mappings: Record<string, string>; zeroArg: string[] };

const generated: Record<string, string> = JSON.parse(
  readFileSync(join(DIR, "generated", "mappings.json"), "utf8"),
);
const custom: CustomMappings = JSON.parse(readFileSync(join(DIR, "custom_mappings.json"), "utf8"));

// Merge generated and custom mappings. The two sets are disjoint - custom mappings are for
// hand-written methods which codegen never emits - so an overlap signals a mistake.
const mappings: Record<string, string> = { ...generated };
for (const [oldName, newPath] of Object.entries(custom.mappings)) {
  if (oldName in mappings) {
    throw new Error(`Custom mapping \`${oldName}\` collides with a generated mapping`);
  }
  mappings[oldName] = newPath;
}

const zeroArg = new Set(custom.zeroArg);

// Build one ast-grep rule (a YAML document) per method, sorted by method name for a stable diff.
const documents = Object.keys(mappings)
  .sort()
  .map((oldName) => buildRuleDoc(oldName, mappings[oldName], zeroArg.has(oldName)));

const header = "# Auto-generated by `generate_rules.mts`. DO NOT EDIT.\n";
const outPath = join(DIR, "generated", "rules.yml");
writeFileSync(outPath, header + documents.join("---\n"));

console.log(`Wrote ${documents.length} rules to ${outPath}`);
console.log(
  "\nApply with:\n  ast-grep scan --rule tasks/ast_builder_migration/generated/rules.yml " +
    "--update-all <target>\n",
);

// Build a single ast-grep rule (one YAML document).
//
// The old builder is reached via `<accessor>.ast` in Oxc (e.g. `self.ast`, `p.ast`), where
// `<accessor>` (`self` / `p`) implements `GetAstBuilder`. The rule matches that access and appends
// `<accessor>` as the new method's final argument. Downstream consumers whose builder is reached
// by a different path should adjust the `pattern` / `fix` templates here.
//
// For methods with arguments, the fix appends `, $ACCESSOR` to the captured args. Two `transform`
// steps prepare the args so this is always valid:
//   1. `NOCOMMENT`: rewrite a trailing line comment on the last arg to a block comment, so the
//      appended `, $ACCESSOR` is not swallowed into the comment (e.g. `x, // c` -> `x /* c */`).
//   2. `CLEANARGS`: strip any trailing comma (common in rustfmt'd multi-line calls), else appending
//      `, $ACCESSOR` would yield a double comma.
// Zero-arg methods omit `$$$ARGS` entirely, else its empty expansion would leave a leading comma
// (`Type::method(, $ACCESSOR)`).
function buildRuleDoc(oldName: string, newPath: string, isZeroArg: boolean): string {
  // `JSON.stringify` yields a double-quoted scalar valid in YAML. `id`s must be unique - the old
  // method name already is.
  const q = (str: string) => JSON.stringify(str);
  const lines = [`id: ${oldName}`, `language: rust`, `rule:`];
  if (isZeroArg) {
    lines.push(
      `  pattern: ${q(`$ACCESSOR.ast.${oldName}()`)}`,
      `fix: ${q(`${newPath}($ACCESSOR)`)}`,
    );
  } else {
    lines.push(
      `  pattern: ${q(`$ACCESSOR.ast.${oldName}($$$ARGS)`)}`,
      `transform:`,
      `  NOCOMMENT:`,
      `    replace:`,
      `      source: ${q("$$$ARGS")}`,
      `      replace: ${q(",\\s*//\\s*(.*)$")}`,
      `      by: ${q(" /* $1 */")}`,
      `  CLEANARGS:`,
      `    replace:`,
      `      source: ${q("$NOCOMMENT")}`,
      `      replace: ${q(",\\s*$")}`,
      `      by: ${q("")}`,
      `fix: ${q(`${newPath}($CLEANARGS, $ACCESSOR)`)}`,
    );
  }
  return `${lines.join("\n")}\n`;
}
